Package = "ai.akemi.appsyncunified_116.0_iphoneos-arm64"
Name = "AppSync Unified (Rootless)"
Version = "166.0"
Architecture = "iphoneos-arm64"
Description = "(Rehosted) Unified AppSync dynamic library for iOS 5 and above."
Maintainer = "Karen aka akemin-dayo <karen@akemi.ai> BlackCat <quanvm0501alt1@tutamail.com>"
Author = "Karen aka akemin-dayo <karen@akemi.ai>"
Section = "Tweaks"
Depends = "mobilesubstrate | com.ex.substitute | ellekit, preferenceloader"
Filename = "C:/Users/Admin/AppData/Local/Temp/jbrepo/deb/ai.akemi.appsyncunified_116.0_iphoneos-arm64.akemi-git-235aca6cddfbdc9fa87fcb5b2aec2df37ed6d65a.deb"