Package = "p3.xyz.yyyue.esign"
Name = "ESign (with AppSync Unified)"
Version = "5.0.2"
Architecture = "iphoneos-arm64"
Description = "ESign App - Sign and install IPA files on iOS."
Maintainer = "Yyyue <yyyue@xyz.p3>"
Author = "Yyyue"
Section = "Applications"
Depends = "mobilesubstrate | com.ex.substitute | ellekit, preferenceloader"
Filename = "p3.xyz.yyyue.esign_5.0.2_iphoneos-arm64.deb"
# SileoDepiction = "http://blackcatofficialytb.github.io/jbrepo/depictions/example.json"